import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";
import { bookingSchema } from "@/lib/validations/booking";

export type BookingStatus = "pending" | "accepted" | "in_progress" | "completed" | "cancelled" | "rejected";

export interface Booking {
  id: string;
  booking_number: string;
  customer_id: string;
  provider_id: string | null;
  service_id: string;
  status: BookingStatus;
  scheduled_date: string;
  scheduled_time: string | null;
  address: string;
  city: string | null;
  pincode: string | null;
  notes: string | null;
  estimated_price: number | null;
  final_price: number | null;
  created_at: string;
  updated_at: string;
  service?: {
    id: string;
    name: string;
    description: string | null;
    base_price: number | null;
    icon: string | null;
    category?: {
      name: string;
      slug: string;
    };
  };
  customer?: {
    full_name: string;
    phone: string | null;
    email: string | null;
  };
  provider?: {
    full_name: string;
    phone: string | null;
  };
}

export interface CreateBookingData {
  service_id: string;
  scheduled_date: string;
  scheduled_time?: string;
  address: string;
  city?: string;
  pincode?: string;
  notes?: string;
  estimated_price?: number;
}

export const useCustomerBookings = () => {
  const { user } = useAuth();

  return useQuery({
    queryKey: ["customer-bookings", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("bookings")
        .select(`
          *,
          service:services(
            id,
            name,
            description,
            base_price,
            icon,
            category:service_categories(name, slug)
          )
        `)
        .eq("customer_id", user!.id)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data as Booking[];
    },
    enabled: !!user,
  });
};

export const useProviderBookings = () => {
  const { user } = useAuth();

  return useQuery({
    queryKey: ["provider-bookings", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("bookings")
        .select(`
          *,
          service:services(
            id,
            name,
            description,
            base_price,
            icon,
            category:service_categories(name, slug)
          )
        `)
        .eq("provider_id", user!.id)
        .order("created_at", { ascending: false });

      if (error) throw error;
      
      // Fetch customer profiles separately due to foreign key naming
      const bookingsWithCustomers = await Promise.all(
        (data || []).map(async (booking) => {
          const { data: customerData } = await supabase
            .from("profiles")
            .select("full_name, phone, email")
            .eq("user_id", booking.customer_id)
            .maybeSingle();
          
          return {
            ...booking,
            customer: customerData || undefined,
          };
        })
      );
      
      return bookingsWithCustomers as Booking[];
    },
    enabled: !!user,
  });
};

export const useCreateBooking = () => {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (bookingData: CreateBookingData) => {
      // Validate input data before sending to database
      const validation = bookingSchema.safeParse(bookingData);
      if (!validation.success) {
        const errorMessages = validation.error.errors.map(e => e.message).join(", ");
        throw new Error(`Validation failed: ${errorMessages}`);
      }

      // Clean the data - remove empty strings for optional fields
      const cleanedData = {
        service_id: validation.data.service_id,
        scheduled_date: validation.data.scheduled_date,
        scheduled_time: validation.data.scheduled_time || null,
        address: validation.data.address.trim(),
        city: validation.data.city?.trim() || null,
        pincode: validation.data.pincode || null,
        notes: validation.data.notes?.trim() || null,
        estimated_price: validation.data.estimated_price || null,
        customer_id: user!.id,
        booking_number: "", // Will be generated by trigger
      };

      const { data, error } = await supabase
        .from("bookings")
        .insert(cleanedData)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["customer-bookings"] });
      toast.success("Booking created successfully!");
    },
    onError: (error) => {
      toast.error("Failed to create booking: " + error.message);
    },
  });
};

export const useUpdateBookingStatus = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ bookingId, status, finalPrice }: { bookingId: string; status: BookingStatus; finalPrice?: number }) => {
      const updateData: Record<string, unknown> = { status };
      if (finalPrice !== undefined) {
        updateData.final_price = finalPrice;
      }

      const { data, error } = await supabase
        .from("bookings")
        .update(updateData)
        .eq("id", bookingId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["customer-bookings"] });
      queryClient.invalidateQueries({ queryKey: ["provider-bookings"] });
      toast.success("Booking status updated!");
    },
    onError: (error) => {
      toast.error("Failed to update booking: " + error.message);
    },
  });
};
